import type {
  Match,
  TeamStats,
} from '@/routes/teams/$teamId/matches/-temp-server-types';

export const mockTeamStats: TeamStats = {
  id: 1,
  name: 'FC서울',
  logo: 'https://matchday2025.s3.ap-northeast-2.amazonaws.com/images/default-team-logo.svg',
  matchesPlayed: 38,
  topScorer: '손흥민',
  wins: 21,
  losses: 13,
  draws: 4,
  goalsFor: 21,
  goalsAgainst: 8,
  recentMatches: ['승', '패', '승', '무', '승'],
};

export const mockMatches: Match[] = [
  {
    id: 1,
    type: '친선경기',
    name: '교내 리그 3R 매치 기록',
    opponentTeam: 'FC수원',
    opponentLogo:
      'https://matchday2025.s3.ap-northeast-2.amazonaws.com/images/default-team-logo.svg',
    result: '승',
    duration: 101,
    location: '서울 성동구 왕십리로 22',
    date: '2025-04-23',
    homeScore: 2,
    awayScore: 1,
  },
  {
    id: 2,
    type: '리그',
    name: '교내 리그 3R 매치 기록',
    opponentTeam: 'FC수원',
    opponentLogo:
      'https://matchday2025.s3.ap-northeast-2.amazonaws.com/images/default-team-logo.svg',
    result: '무',
    duration: 101,
    location: '서울 성동구 왕십리로 22',
    date: '2025-04-23',
    homeScore: 1,
    awayScore: 1,
  },
  {
    id: 3,
    type: '대회',
    name: '교내 리그 3R 매치 기록',
    opponentTeam: 'FC수원',
    opponentLogo:
      'https://matchday2025.s3.ap-northeast-2.amazonaws.com/images/default-team-logo.svg',
    result: '패',
    duration: 101,
    location: '서울 성동구 왕십리로 22',
    date: '2025-04-23',
    homeScore: 0,
    awayScore: 2,
  },
  {
    id: 4,
    type: '친선경기',
    name: '교내 리그 3R 매치 기록',
    opponentTeam: 'FC수원',
    opponentLogo:
      'https://matchday2025.s3.ap-northeast-2.amazonaws.com/images/default-team-logo.svg',
    result: '패',
    duration: 101,
    location: '서울 성동구 왕십리로 22',
    date: '2025-04-23',
    homeScore: 1,
    awayScore: 3,
  },
  {
    id: 5,
    type: '친선경기',
    name: '교내 리그 3R 매치 기록',
    opponentTeam: 'FC수원',
    opponentLogo:
      'https://matchday2025.s3.ap-northeast-2.amazonaws.com/images/default-team-logo.svg',
    result: '패',
    duration: 101,
    location: '서울 성동구 왕십리로 22',
    date: '2025-04-23',
    homeScore: 0,
    awayScore: 1,
  },
  {
    id: 6,
    type: '친선경기',
    name: '교내 리그 3R 매치 기록',
    opponentTeam: 'FC수원',
    opponentLogo:
      'https://matchday2025.s3.ap-northeast-2.amazonaws.com/images/default-team-logo.svg',
    result: '승',
    duration: 101,
    location: '서울 성동구 왕십리로 22',
    date: '2025-04-23',
    homeScore: 3,
    awayScore: 1,
  },
  {
    id: 7,
    type: '친선경기',
    name: '교내 리그 3R 매치 기록',
    opponentTeam: 'FC수원',
    opponentLogo:
      'https://matchday2025.s3.ap-northeast-2.amazonaws.com/images/default-team-logo.svg',
    result: '승',
    duration: 101,
    location: '서울 성동구 왕십리로 22',
    date: '2025-04-23',
    homeScore: 2,
    awayScore: 0,
  },
  {
    id: 8,
    type: '친선경기',
    name: '교내 리그 3R 매치 기록',
    opponentTeam: 'FC수원',
    opponentLogo:
      'https://matchday2025.s3.ap-northeast-2.amazonaws.com/images/default-team-logo.svg',
    result: '승',
    duration: 101,
    location: '서울 성동구 왕십리로 22',
    date: '2025-04-23',
    homeScore: 4,
    awayScore: 2,
  },
];
