/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * MatchDay Swagger
 * MatchDay 요구사항에 대한 REST API
 * OpenAPI spec version: 0.0.1
 */
import type { MatchListResponse } from './MatchListResponse';

export interface ApiResponseListMatchListResponse {
  status?: number;
  data?: MatchListResponse[];
  message?: string;
}
