/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * MatchDay Swagger
 * MatchDay 요구사항에 대한 REST API
 * OpenAPI spec version: 0.0.1
 */

export interface MatchInfoResponse {
  /** id */
  id: number;
  /** 홈팀 ID */
  homeTeamId: number;
  /** 어웨이팀 ID */
  awayTeamId: number;
  /** 장소 */
  stadium: string;
  /** 날짜 */
  matchDate: string;
  startTime: string;
  endTime: string;
  /** 주심 */
  mainRefereeName: string;
  /** 부심1 */
  assistantReferee1: string;
  /** 부심2 */
  assistantReferee2: string;
  /** 대기심 */
  fourthReferee: string;
  firstHalfStartTime: string;
  secondHalfStartTime: string;
}
