/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * MatchDay Swagger
 * 개발용 Swagger API 문서
 * OpenAPI spec version: 0.0.1
 */
import type { MatchListResponse } from './MatchListResponse';

/**
 * 페이징용 매치 리스트 응답 객체
 */
export interface MatchListPageResponse {
  /** 전체 매치 개수 */
  totalCount: number;
  /** 현재 페이지 매치 리스트 */
  matches: MatchListResponse[];
}
