/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * MatchDay Swagger
 * MatchDay 요구사항에 대한 REST API
 * OpenAPI spec version: 0.0.1
 */

/**
 * 경기 상태 (SCHEDULED, ONGOING, FINISHED)
 */
export type MatchCreateRequestMatchState =
  (typeof MatchCreateRequestMatchState)[keyof typeof MatchCreateRequestMatchState];

export const MatchCreateRequestMatchState = {
  SCHEDULED: 'SCHEDULED',
  IN_PLAY: 'IN_PLAY',
  FINISHED: 'FINISHED',
} as const;
