/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * MatchDay Swagger
 * 개발용 Swagger API 문서
 * OpenAPI spec version: 0.0.1
 */

/**
 * 매치 결과
 */
export type MatchResultInfoResponseMatchResult =
  (typeof MatchResultInfoResponseMatchResult)[keyof typeof MatchResultInfoResponseMatchResult];

export const MatchResultInfoResponseMatchResult = {
  WIN: 'WIN',
  LOSE: 'LOSE',
  DRAW: 'DRAW',
} as const;
