/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * MatchDay Swagger
 * MatchDay 요구사항에 대한 REST API
 * OpenAPI spec version: 0.0.1
 */
import type { MatchListResponseMatchState } from './MatchListResponseMatchState';

export interface MatchListResponse {
  /** 매치 ID */
  matchId: number;
  /** 홈팀 ID */
  homeTeamId: number;
  /** 홈팀명 */
  homeTeamName: string;
  /** 상대팀 ID */
  awayTeamId: number;
  /** 상대팀명 */
  awayTeamName: string;
  /** 매치명 */
  matchTitle: string;
  matchStartTime: string;
  matchEndTime: string;
  /** 매치 장소 */
  stadium: string;
  /** 홈팀 스코어 */
  homeScore: number;
  /** 상대팀 스코어 */
  awayScore: number;
  /** 경기 진행 여부 */
  matchState: MatchListResponseMatchState;
}
