/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * MatchDay Swagger
 * MatchDay 요구사항에 대한 REST API
 * OpenAPI spec version: 0.0.1
 */
import type { MatchHalfTimeRequestHalfType } from './MatchHalfTimeRequestHalfType';
import type { MatchHalfTimeRequestTimeType } from './MatchHalfTimeRequestTimeType';

export interface MatchHalfTimeRequest {
  /** 전/후반  */
  halfType: MatchHalfTimeRequestHalfType;
  /** 시작/종료 시간 */
  timeType: MatchHalfTimeRequestTimeType;
  time: string;
}
