/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * MatchDay Swagger
 * 개발용 Swagger API 문서
 * OpenAPI spec version: 0.0.1
 */
import type { MatchResultInfoResponseMatchResult } from './MatchResultInfoResponseMatchResult';

/**
 * 매치 결과 정보 응답 객체
 */
export interface MatchResultInfoResponse {
  /** 매치 ID */
  matchId: number;
  /** 홈팀 ID */
  homeTeamId: number;
  /** 홈팀명 */
  homeTeamName: string;
  /** 상대팀 ID */
  awayTeamId: number;
  /** 상대팀명 */
  awayTeamName: string;
  /** 매치명 */
  matchTitle: string;
  /** 매치 결과 */
  matchResult: MatchResultInfoResponseMatchResult;
  /** 홈팀 스코어 */
  homeScore: number;
  /** 상대팀 스코어 */
  awayScore: number;
  /** 경기 시간 */
  matchTime: number;
  /** 출전 선수 */
  playerCount: number;
  /** 매치 장소 */
  stadium: string;
  /** 경기 일시 */
  matchDate: string;
}
