/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * MatchDay Swagger
 * 개발용 Swagger API 문서
 * OpenAPI spec version: 0.0.1
 */
import type { MatchEventResponseEventLog } from './MatchEventResponseEventLog';

/**
 * 경기 이벤트 응답 DTO
 */
export interface MatchEventResponse {
  /** 이벤트 ID */
  id: number;
  /** 경기 시작 후 경과 시간(분) */
  elapsedMinutes: number;
  /** 전반/후반 여부 */
  halfType: string;
  /** 팀 ID */
  teamId: number;
  /** 팀 이름 */
  teamName: string;
  /** 선수 ID */
  userId: number;
  /** 선수 이름 */
  userName: string;
  /** 경기 이벤트 타입 */
  eventLog: MatchEventResponseEventLog;
}
