/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * MatchDay Swagger
 * 개발용 Swagger API 문서
 * OpenAPI spec version: 0.0.1
 */

/**
 * 매치 정보 응답 객체
 */
export interface MatchInfoResponse {
  /** id */
  id: number;
  /** 홈팀 ID */
  homeTeamId: number;
  /** 어웨이팀 ID */
  awayTeamId: number;
  /** 경기명 */
  title: string;
  /** 장소 */
  stadium: string;
  /** 날짜 */
  matchDate: string;
  plannedStartTime: string;
  plannedEndTime: string;
  /** 전반 진행 시간 (분) */
  firstHalfPeriod: number;
  /** 후반 진행 시간 (분) */
  secondHalfPeriod: number;
  /**
   * 주심
   * @nullable
   */
  mainRefereeName: string | null;
  /**
   * 부심1
   * @nullable
   */
  assistantReferee1: string | null;
  /**
   * 부심2
   * @nullable
   */
  assistantReferee2: string | null;
  /**
   * 대기심
   * @nullable
   */
  fourthReferee: string | null;
  firstHalfStartTime: string;
  firstHalfEndTime: string;
  secondHalfStartTime: string;
  secondHalfEndTime: string;
}
