/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * MatchDay Swagger
 * MatchDay 요구사항에 대한 REST API
 * OpenAPI spec version: 0.0.1
 */

/**
 * 경기 이벤트 타입
 */
export type MatchEventResponseEventLog =
  (typeof MatchEventResponseEventLog)[keyof typeof MatchEventResponseEventLog];

export const MatchEventResponseEventLog = {
  GOAL: 'GOAL',
  ASSIST: 'ASSIST',
  SHOT: 'SHOT',
  CORNER_KICK: 'CORNER_KICK',
  VALID_SHOT: 'VALID_SHOT',
  FOUL: 'FOUL',
  OFFSIDE: 'OFFSIDE',
  SUB_IN: 'SUB_IN',
  SUB_OUT: 'SUB_OUT',
  YELLOW_CARD: 'YELLOW_CARD',
  RED_CARD: 'RED_CARD',
  OWN_GOAL: 'OWN_GOAL',
  WARNING: 'WARNING',
} as const;
