/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * MatchDay Swagger
 * MatchDay 요구사항에 대한 REST API
 * OpenAPI spec version: 0.0.1
 */
import type { MatchUserCreateRequestRole } from './MatchUserCreateRequestRole';

/**
 * 매치 참가자 생성 요청
 */
export interface MatchUserCreateRequest {
  /** 사용자 ID */
  userId: number;
  /** 팀 ID */
  teamId: number;
  /** 매치에서의 역할 */
  role: MatchUserCreateRequestRole;
  /** 매치에서의 포지션 */
  matchPosition: string;
  /** 매치에서의 그리드 위치 */
  matchGrid: string;
}
