/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * MatchDay Swagger
 * MatchDay 요구사항에 대한 REST API
 * OpenAPI spec version: 0.0.1
 */

export interface MatchUserGridUpdateRequest {
  /**
   * 매치에서의 선수 그리드 좌표
   * @minimum 0
   * @maximum 29
   */
  matchGrid: number;
}
