/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * MatchDay Swagger
 * 개발용 Swagger API 문서
 * OpenAPI spec version: 0.0.1
 */

/**
 * 매치별 메모 응답 객체
 */
export interface MatchMemoResponse {
  /** 메모id */
  matchId: number;
  /**
   * 메모
   * @nullable
   */
  memo: string | null;
}
