/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * MatchDay Swagger
 * MatchDay 요구사항에 대한 REST API
 * OpenAPI spec version: 0.0.1
 */
import type { MatchUserCreateRequestRole } from './MatchUserCreateRequestRole';

/**
 * 매치 참가자 생성 요청
 */
export interface MatchUserCreateRequest {
  /** 사용자 ID */
  userId: number;
  /**
   * 팀 ID
   * @nullable
   */
  teamId: number | null;
  /** 매치에서의 역할 */
  role: MatchUserCreateRequestRole;
  /**
   * 매치에서의 포지션
   * @nullable
   */
  matchPosition: string | null;
  /**
   * 매치에서의 선수 그리드 좌표(0~29)
   * @minimum 0
   * @maximum 29
   * @nullable
   */
  matchGrid: number | null;
}
