/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * MatchDay Swagger
 * MatchDay 요구사항에 대한 REST API
 * OpenAPI spec version: 0.0.1
 */
import type { TeamGroupedUsers } from './TeamGroupedUsers';

/**
 * 홈팀과 어웨이팀 참가자 정보를 선발/교체로 그룹핑한 응답
 */
export interface MatchUserGroupResponse {
  homeTeam?: TeamGroupedUsers;
  awayTeam?: TeamGroupedUsers;
}
