/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * MatchDay Swagger
 * MatchDay 요구사항에 대한 REST API
 * OpenAPI spec version: 0.0.1
 */
import type { ScoreResponse } from './ScoreResponse';

/**
 * 경기 점수 응답 객체
 */
export interface MatchScoreResponse {
  /** 경기 ID */
  matchId?: number;
  /** 홈팀 ID */
  homeTeamId?: number;
  /** 상대팀 ID */
  awayTeamId?: number;
  homeScore?: ScoreResponse;
  awayScore?: ScoreResponse;
}
