/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * MatchDay Swagger
 * MatchDay 요구사항에 대한 REST API
 * OpenAPI spec version: 0.0.1
 */

/**
 * 매치 참가자 통계 응답
 */
export interface MatchUserResponse {
  /** 유저 ID */
  id?: number;
  /** 유저 이름 */
  name?: string;
  /** 등번호 */
  number?: number;
  /** 매치 포지션 */
  matchPosition?: string;
  /** 경기장 그리드 위치 */
  matchGrid?: string;
  /** 득점 수 */
  goals?: number;
  /** 어시스트 수 */
  assists?: number;
  /** 옐로카드 수 */
  yellowCards?: number;
  /** 레드카드 수 */
  redCards?: number;
  /** 경고 누적 수 (옐로카드 개수) */
  caution?: number;
  /** 퇴장 여부 (옐로 2장 이상 또는 레드 1장 이상) */
  sentOff?: boolean;
}
