/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * MatchDay Swagger
 * MatchDay 요구사항에 대한 REST API
 * OpenAPI spec version: 0.0.1
 */

/**
 * 프로필 사진 등록/조회 URL 응답
 */
export interface S3PresignedResponse {
  /** 프로필 등록/조회 URL */
  url: string;
}
