/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * MatchDay Swagger
 * MatchDay 요구사항에 대한 REST API
 * OpenAPI spec version: 0.0.1
 */

/**
 * 경기 중 다양한 이벤트 발생 횟수 응답 객체
 */
export interface ScoreResponse {
  /** 골 횟수 */
  goalCount?: number;
  /** 슈팅 횟수 */
  shotCount?: number;
  /** 유효 슈팅 횟수 */
  validShotCount?: number;
  /** 코너킥 횟수 */
  cornerKickCount?: number;
  /** 오프사이드 횟수 */
  offsideCount?: number;
  /** 파울 횟수 */
  foulCount?: number;
  /** 경고 횟수 */
  warningCount?: number;
}
