/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * MatchDay Swagger
 * 개발용 Swagger API 문서
 * OpenAPI spec version: 0.0.1
 */

/**
 * 팀 멤버 응답 객체
 */
export interface TeamMemberResponse {
  /** 팀 멤버 ID */
  id: number;
  /** 멤버 이름 */
  name: string;
  /**
   * 선수 Number
   * @nullable
   */
  number: number | null;
  /**
   * 고정 포지션
   * @nullable
   */
  defaultPosition: string | null;
  /**
   * 현재 팀에서 활동 여부
   * @nullable
   */
  isActive: boolean | null;
  /**
   * 프로필 이미지
   * @nullable
   */
  imageUrl: string | null;
  /** 누적 출전수 */
  totalAppearances: number;
  /** 누적 득점수 */
  totalGoals: number;
  /** 누적 경고수 */
  totalWarnings: number;
}
