/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * MatchDay Swagger
 * MatchDay 요구사항에 대한 REST API
 * OpenAPI spec version: 0.0.1
 */
import type { MatchUserResponse } from './MatchUserResponse';

/**
 * 선발 및 교체 참가자 그룹
 */
export interface TeamGroupedUsers {
  /** 선발 선수 목록 */
  starters: MatchUserResponse[];
  /** 교체 선수 목록 */
  substitutes: MatchUserResponse[];
}
