/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * MatchDay Swagger
 * MatchDay 요구사항에 대한 REST API
 * OpenAPI spec version: 0.0.1
 */

export interface TeamCreateRequest {
  /**
   * 팀 이름
   * @minLength 1
   */
  name: string;
  /**
   * 팀 컬러(상의 컬러)
   * @minLength 1
   */
  teamColor: string;
  /**
   * 팀 하의 컬러
   * @minLength 1
   */
  bottomColor: string;
  /**
   * 팀 스타킹 컬러
   * @minLength 1
   */
  stockingColor: string;
  /**
   * 팀 이미지명
   * @nullable
   */
  teamImg: string | null;
}
