/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * MatchDay Swagger
 * 개발용 Swagger API 문서
 * OpenAPI spec version: 0.0.1
 */

export interface UserCreateRequest {
  /**
   * 유저 이름
   * @minLength 1
   */
  name: string;
  /**
   * 유저 프로필 이미지명
   * @nullable
   */
  profileImg: string | null;
}
