/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * MatchDay Swagger
 * MatchDay 요구사항에 대한 REST API
 * OpenAPI spec version: 0.0.1
 */

export interface UserJoinTeamRequest {
  /** 가입할 팀의 ID */
  teamId: number;
  /**
   * 선수의 등번호
   * @nullable
   */
  number: number | null;
  /**
   * 선수의 팀 내 포지션
   * @nullable
   */
  defaultPosition: string | null;
}
