import type {
  MatchRecord,
  Member,
} from '@/routes/teams/$teamId/players/-temp-server-types';

export const mockMembers: Member[] = [
  {
    id: 1,
    name: '손흥민',
    number: '#7',
    position: 'FW',
    foot: '왼발',
    role: '관리자',
    joinDate: '2025-04-23',
    profileImage: null,
    birthDate: '1992-07-08',
    height: 183,
    weight: 77,
    secondaryPosition: 'MF',
  },
  {
    id: 2,
    name: '손흥민',
    number: '#7',
    position: 'MF',
    foot: '오른발',
    role: '일반',
    joinDate: '2025-04-23',
    profileImage: null,
    birthDate: '1992-07-08',
    height: 183,
    weight: 77,
    secondaryPosition: 'FW',
  },
  {
    id: 3,
    name: '손흥민',
    number: '#7',
    position: 'DF',
    foot: '양발',
    role: '일반',
    joinDate: '2025-04-23',
    profileImage: null,
    birthDate: '1992-07-08',
    height: 183,
    weight: 77,
    secondaryPosition: 'MF',
  },
  {
    id: 4,
    name: '손흥민',
    number: '#7',
    position: 'GK',
    foot: '양발',
    role: '일반',
    joinDate: '2025-04-23',
    profileImage: null,
    birthDate: '1992-07-08',
    height: 183,
    weight: 77,
    secondaryPosition: 'DF',
  },
  {
    id: 5,
    name: '손흥민',
    number: '#7',
    position: 'FW',
    foot: '양발',
    role: '일반',
    joinDate: '2025-04-23',
    profileImage: null,
    birthDate: '1992-07-08',
    height: 183,
    weight: 77,
    secondaryPosition: 'MF',
  },
  {
    id: 6,
    name: '손흥민',
    number: '#7',
    position: 'FW',
    foot: '양발',
    role: '일반',
    joinDate: '2025-04-23',
    profileImage: null,
    birthDate: '1992-07-08',
    height: 183,
    weight: 77,
    secondaryPosition: 'MF',
  },
  {
    id: 7,
    name: '손흥민',
    number: '#7',
    position: 'FW',
    foot: '양발',
    role: '일반',
    joinDate: '2025-04-23',
    profileImage: null,
    birthDate: '1992-07-08',
    height: 183,
    weight: 77,
    secondaryPosition: null,
  },
  {
    id: 8,
    name: '손흥민',
    number: '#7',
    position: 'FW',
    foot: '양발',
    role: '일반',
    joinDate: '2025-04-23',
    profileImage: null,
    birthDate: '1992-07-08',
    height: 183,
    weight: 77,
    secondaryPosition: 'MF',
  },
];

export const mockMatchRecords: MatchRecord[] = [
  {
    id: 1,
    opponentTeam: 'FC 수원',
    opponentLogo:
      'https://matchday2025.s3.ap-northeast-2.amazonaws.com/images/default-team-logo.svg',
    homeScore: 2,
    awayScore: 1,
    isWin: false,
    goals: 1,
    assists: 1,
    yellowCards: 0,
    redCards: 1,
  },
  {
    id: 2,
    opponentTeam: 'FC 수원',
    opponentLogo:
      'https://matchday2025.s3.ap-northeast-2.amazonaws.com/images/default-team-logo.svg',
    homeScore: 2,
    awayScore: 1,
    isWin: false,
    goals: 1,
    assists: 0,
    yellowCards: 0,
    redCards: 1,
  },
  {
    id: 3,
    opponentTeam: 'FC 수원',
    opponentLogo:
      'https://matchday2025.s3.ap-northeast-2.amazonaws.com/images/default-team-logo.svg',
    homeScore: 2,
    awayScore: 1,
    isWin: false,
    goals: 1,
    assists: 2,
    yellowCards: 1,
    redCards: 0,
  },
  {
    id: 4,
    opponentTeam: 'FC 수원',
    opponentLogo:
      'https://matchday2025.s3.ap-northeast-2.amazonaws.com/images/default-team-logo.svg',
    homeScore: 2,
    awayScore: 1,
    isWin: false,
    goals: 1,
    assists: 0,
    yellowCards: 1,
    redCards: 1,
  },
  {
    id: 5,
    opponentTeam: 'FC 수원',
    opponentLogo:
      'https://matchday2025.s3.ap-northeast-2.amazonaws.com/images/default-team-logo.svg',
    homeScore: 1,
    awayScore: 2,
    isWin: true,
    goals: 1,
    assists: 3,
    yellowCards: 0,
    redCards: 1,
  },
  {
    id: 6,
    opponentTeam: 'FC 수원',
    opponentLogo:
      'https://matchday2025.s3.ap-northeast-2.amazonaws.com/images/default-team-logo.svg',
    homeScore: 1,
    awayScore: 2,
    isWin: true,
    goals: 1,
    assists: 0,
    yellowCards: 0,
    redCards: 1,
  },
  {
    id: 7,
    opponentTeam: 'FC 수원',
    opponentLogo:
      'https://matchday2025.s3.ap-northeast-2.amazonaws.com/images/default-team-logo.svg',
    homeScore: 1,
    awayScore: 2,
    isWin: true,
    goals: 1,
    assists: 0,
    yellowCards: 0,
    redCards: 1,
  },
  {
    id: 8,
    opponentTeam: 'FC 수원',
    opponentLogo:
      'https://matchday2025.s3.ap-northeast-2.amazonaws.com/images/default-team-logo.svg',
    homeScore: 1,
    awayScore: 2,
    isWin: true,
    goals: 1,
    assists: 0,
    yellowCards: 0,
    redCards: 1,
  },
  {
    id: 9,
    opponentTeam: 'FC 수원',
    opponentLogo:
      'https://matchday2025.s3.ap-northeast-2.amazonaws.com/images/default-team-logo.svg',
    homeScore: 1,
    awayScore: 2,
    isWin: true,
    goals: 1,
    assists: 0,
    yellowCards: 0,
    redCards: 1,
  },
];

export const mockPersonalInfo = {
  birthDate: '1992.07.08',
  height: 183,
  weight: 77,
};

export const mockSecondaryPosition = 'MF';
